//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stokTakip021Entities1 : DbContext
    {
        public stokTakip021Entities1()
            : base("name=stokTakip021Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbbirim> dbbirims { get; set; }
        public virtual DbSet<dbkategori> dbkategoris { get; set; }
        public virtual DbSet<dbmarka> dbmarkas { get; set; }
        public virtual DbSet<dbmusteri> dbmusteris { get; set; }
        public virtual DbSet<dbSatislar> dbSatislars { get; set; }
        public virtual DbSet<dbsepet> dbsepets { get; set; }
        public virtual DbSet<dburunler> dburunlers { get; set; }
        public virtual DbSet<dbuser> dbusers { get; set; }
        public virtual DbSet<ilceler> ilcelers { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<login> logins { get; set; }
    }
}
